### ISSUE TITLE
Внешний вид и баги

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/plugin-range-slider#1]
1. Сделать покрупнее. Слишком мелко.

**Comment by EvgeniyChuprov** [comment]
При вводе неверных значений ведет себя странно)
![Peek 2019-12-26 11-18](https://user-images.githubusercontent.com/36810364/71466771-ab12b700-27d1-11ea-91bb-8df852f2a4f1.gif)

Клики по чекбоксам происходят далеко за их пределами
![Peek 2019-12-26 11-24](https://user-images.githubusercontent.com/36810364/71466961-44da6400-27d2-11ea-8dc3-a226fe70214d.gif)
Отображаются значения без ползунков, и самого слайдера.
![Peek 2019-12-26 11-26](https://user-images.githubusercontent.com/36810364/71467057-9da9fc80-27d2-11ea-8096-731114015203.gif)
Слайдер уходит за пределы экрана
![Снимок экрана от 2019-12-26 11-27-51](https://user-images.githubusercontent.com/36810364/71467101-d4801280-27d2-11ea-8c85-ba636822b722.png)

Ну и по логике меньший ползунок не должен заходить за больший.

**Comment by EvgeniyChuprov** [comment]
При совмещении ползунков невозможно переместить меньший.
+ Реализовать перемещение по клику по шкале слайдера.    
![Peek 2020-01-31 14-22](https://user-images.githubusercontent.com/36810364/73535658-27ce2c00-4435-11ea-810f-7ae882fd5a65.gif)

**Comment by EvgeniyChuprov** [comment]
При клике ползунок должен вставать на ближайший к месту клика шаг.
![Peek 2020-02-24 14-25](https://user-images.githubusercontent.com/36810364/75148832-9d19dd80-5711-11ea-9903-a02a9c434ba1.gif)

**Comment by Vodkamishka** [comment]
> При клике ползунок должен вставать на ближайший к месту клика шаг.
> ![Peek 2020-02-24 14-25](https://user-images.githubusercontent.com/36810364/75148832-9d19dd80-5711-11ea-9903-a02a9c434ba1.gif)

исправил

**Comment by EvgeniyChuprov** [comment]
С вертикальным расположением не работает
![Peek 2020-02-27 10-43](https://user-images.githubusercontent.com/36810364/75422664-29184900-594e-11ea-8f06-ce2005c4ab73.gif)

**Comment by Vodkamishka** [comment]
> С вертикальным расположением не работает
> ![Peek 2020-02-27 10-43](https://user-images.githubusercontent.com/36810364/75422664-29184900-594e-11ea-8f06-ce2005c4ab73.gif)

исправил
