### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/plugin-range-slider#3]
Маргин в блоке + px.
![Снимок экрана от 2020-01-31 14-25-01](https://user-images.githubusercontent.com/36810364/73535808-885d6900-4435-11ea-80d5-9ab0876ce821.png)

**Comment by Vodkamishka** [comment]
Исправил

**Comment by Vodkamishka** [comment]
> Маргин в блоке + px.
> ![Снимок экрана от 2020-01-31 14-25-01](https://user-images.githubusercontent.com/36810364/73535808-885d6900-4435-11ea-80d5-9ab0876ce821.png)

Исправил

**Comment by Vodkamishka** [comment]
Исправил

**Comment by EvgeniyChuprov** [comment]
Внешнее позиционирование запрещено. В остальных блоках так же.
![Снимок экрана от 2020-02-14 14-05-58](https://user-images.githubusercontent.com/36810364/74525844-291e4f00-4f33-11ea-91ee-ebe57e8b1774.png)

**Comment by Vodkamishka** [comment]
Исправил
