### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/plugin-range-slider#4]
Код должен соответствовать стандартам fsd и стайлгайду AirBnB, в том числе и по оформлению.
Поставить ESlint и настроить его на правила AirBnB.
Большое количество аргументов передавать объектом и деструктуризировать их внутри функции или метода.
![Снимок экрана от 2020-02-03 13-51-04](https://user-images.githubusercontent.com/36810364/73647351-55f97900-468c-11ea-9ebe-4b452476d4b7.png)

**Comment by EvgeniyChuprov** [comment]
По стандартам airbnb, для приведения к числу нужно использовать Number:
![Снимок экрана от 2020-02-07 14-23-04](https://user-images.githubusercontent.com/36810364/74025601-62940f00-49b5-11ea-885a-9d980e02f5cf.png)

**Comment by EvgeniyChuprov** [comment]
Экспорты по стандартам должны располагаться внизу страницы.
Большое количество аргументов заменяется на на один аргумент объект.
![Снимок экрана от 2020-02-13 11-37-08](https://user-images.githubusercontent.com/36810364/74415880-4846af00-4e55-11ea-8d78-2262aaa97b1f.png)
+ Для чего они?

**Comment by EvgeniyChuprov** [comment]
Числа в названиях не использовать.
![Снимок экрана от 2020-02-13 11-40-58](https://user-images.githubusercontent.com/36810364/74416148-bd19e900-4e55-11ea-9d52-ef19d135d020.png)

**Comment by Vodkamishka** [comment]
> По стандартам airbnb, для приведения к числу нужно использовать Number:
> ![Снимок экрана от 2020-02-07 14-23-04](https://user-images.githubusercontent.com/36810364/74025601-62940f00-49b5-11ea-885a-9d980e02f5cf.png)

Исправил

**Comment by Vodkamishka** [comment]
> Экспорты по стандартам должны располагаться внизу страницы.
> Большое количество аргументов заменяется на на один аргумент объект.
> ![Снимок экрана от 2020-02-13 11-37-08](https://user-images.githubusercontent.com/36810364/74415880-4846af00-4e55-11ea-8d78-2262aaa97b1f.png)
> 
> * Для чего они?

Исправил. Для тестирования.

**Comment by Vodkamishka** [comment]
> Числа в названиях не использовать.
> ![Снимок экрана от 2020-02-13 11-40-58](https://user-images.githubusercontent.com/36810364/74416148-bd19e900-4e55-11ea-9d52-ef19d135d020.png)

Исправил

**Comment by Vodkamishka** [comment]
> По стандартам airbnb, для приведения к числу нужно использовать Number:
> ![Снимок экрана от 2020-02-07 14-23-04](https://user-images.githubusercontent.com/36810364/74025601-62940f00-49b5-11ea-885a-9d980e02f5cf.png)

Исправил

**Comment by Vodkamishka** [comment]
> Код должен соответствовать стандартам fsd и стайлгайду AirBnB, в том числе и по оформлению.
> Поставить ESlint и настроить его на правила AirBnB.
> Большое количество аргументов передавать объектом и деструктуризировать их внутри функции или метода.
> ![Снимок экрана от 2020-02-03 13-51-04](https://user-images.githubusercontent.com/36810364/73647351-55f97900-468c-11ea-9ebe-4b452476d4b7.png)

В данном месте деструктуризация проведена быть не может, так как она проведена ниже в функции и переменные уже декларированы ниже, повторное объявление переменных приводит к ошибке

**Comment by EvgeniyChuprov** [comment]
Если речь об этом, то тут  также аргумент нужно привести к объекту
![Снимок экрана от 2020-02-14 14-12-45](https://user-images.githubusercontent.com/36810364/74526396-62a38a00-4f34-11ea-830c-58a33f70d86c.png)
с остальными функциями поступать так же.

**Comment by EvgeniyChuprov** [comment]
Вынести панель в отдельную директорию, она к mvc не относится.
![Снимок экрана от 2020-02-14 14-16-45](https://user-images.githubusercontent.com/36810364/74526592-bada8c00-4f34-11ea-8349-736c51d63414.png)

**Comment by Vodkamishka** [comment]
> Вынести панель в отдельную директорию, она к mvc не относится.
> ![Снимок экрана от 2020-02-14 14-16-45](https://user-images.githubusercontent.com/36810364/74526592-bada8c00-4f34-11ea-8349-736c51d63414.png)

Сделал

**Comment by Vodkamishka** [comment]
> Вынести панель в отдельную директорию, она к mvc не относится.
> ![Снимок экрана от 2020-02-14 14-16-45](https://user-images.githubusercontent.com/36810364/74526592-bada8c00-4f34-11ea-8349-736c51d63414.png)

Исправил

**Comment by Vodkamishka** [comment]
> Если речь об этом, то тут также аргумент нужно привести к объекту
> ![Снимок экрана от 2020-02-14 14-12-45](https://user-images.githubusercontent.com/36810364/74526396-62a38a00-4f34-11ea-830c-58a33f70d86c.png)
> с остальными функциями поступать так же.

Переделал

**Comment by EvgeniyChuprov** [comment]
![Снимок экрана от 2020-02-17 14-32-19](https://user-images.githubusercontent.com/36810364/74650261-5caae480-5192-11ea-8e5a-f6b0a0656d65.png)
Все плагины и библиотеки подключаются через webpack.

**Comment by Vodkamishka** [comment]
> ![Снимок экрана от 2020-02-17 14-32-19](https://user-images.githubusercontent.com/36810364/74650261-5caae480-5192-11ea-8e5a-f6b0a0656d65.png)
> Все плагины и библиотеки подключаются через webpack.

Исправил
