### ISSUE TITLE
tslint

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/plugin-range-slider#5]
Убрать эти правила и привести к стандартам.
![Снимок экрана от 2020-02-14 14-08-00](https://user-images.githubusercontent.com/36810364/74525971-6f73ae00-4f33-11ea-9275-cb875463fa00.png)

**Comment by Vodkamishka** [comment]
Исправил

**Comment by EvgeniyChuprov** [comment]
Смысл линтера в том, что бы писать по стандарту, а не отключать его правки.
почему например когда он ругается на длину строки
![Снимок экрана от 2020-02-17 14-09-32](https://user-images.githubusercontent.com/36810364/74648805-6bdc6300-518f-11ea-9da6-9364eaec1e7b.png)
не записать это как то так.
![Снимок экрана от 2020-02-17 14-09-19](https://user-images.githubusercontent.com/36810364/74648789-641cbe80-518f-11ea-99b4-487ed2e5d271.png)
либо тут
![Снимок экрана от 2020-02-17 14-15-24](https://user-images.githubusercontent.com/36810364/74649114-0472e300-5190-11ea-8b61-4d0a4c2035c4.png)
сделать так
![Снимок экрана от 2020-02-17 14-15-11](https://user-images.githubusercontent.com/36810364/74649132-0ccb1e00-5190-11ea-8fd7-82b568a9d0d9.png)

Поправить для всех случаев.

**Comment by Vodkamishka** [comment]
Все исправил, кроме правила "import-name".  Оно заставляет экспортировать классы с с маленькой буквы.

**Comment by EvgeniyChuprov** [comment]
Достаточно переименовать файл с классом.
![Снимок экрана от 2020-02-18 12-18-09](https://user-images.githubusercontent.com/36810364/74721647-c4bc0200-5248-11ea-993c-ee770a728546.png)

**Comment by Vodkamishka** [comment]
> Достаточно переименовать файл с классом.
> ![Снимок экрана от 2020-02-18 12-18-09](https://user-images.githubusercontent.com/36810364/74721647-c4bc0200-5248-11ea-993c-ee770a728546.png)

Переделал
